name: 'Github Pages Org Sync'
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  org-sync:
    permissions:
      # Needed for deployment
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1

      - name: Generate HTML
        run: ./org-publish-config.el

      - name: Zipping Files for Upload
        run: tar -zcvf artifact.tar.gz ./out

      - name: Upload Files
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: artifact.tar.gz

      - name: Deploy Files
        uses: actions/deploy-pages@v1
        id: deployment          # Used above in the environment to set the url
  
